### ISSUE TITLE
Download not working, always returning 418 Blocked

### ISSUE THREAD

**Issue by derMart** [baurls/TileStitcher#2]
The quick_start.py and also advanced.py examples do not work. Even when changing the zoom level to 1, so that only one tile is downloaded they get blocked by the tile server:
```
INFO:map_tile_stitcher.util.tile_loading:Downloading 1 tiles to disk (in parallel)..
   0%|□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□|Process LokyProcess-4:
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/map_tile_stitcher/util/tile_loading.py", line 56, in _download_tile_in_parallel
    _trigger_download(url, file_name)
  File "/home/martin/.local/lib/python3.10/site-packages/map_tile_stitcher/util/tile_loading.py", line 80, in _trigger_download
    response = urllib.request.urlopen(request)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 418: Blocked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    result_queue.put(_ResultItem(call_item.work_id, exception=exc))
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/queues.py", line 186, in put
    obj = dumps(obj, reducers=self._reducers)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 211, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 204, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_io.BufferedReader' object
Traceback (most recent call last):
  File "/home/martin/repos/map-tiler/tyler.py", line 15, in <module>
    stitcher.download_and_stitch(start, end, zoom)
  File "/home/martin/.local/lib/python3.10/site-packages/map_tile_stitcher/util/quick_start.py", line 24, in download_and_stitch
    self.downloader.download_tiles(grid_bb)
  File "/home/martin/.local/lib/python3.10/site-packages/map_tile_stitcher/util/tile_loading.py", line 45, in download_tiles
    parallel_pool(delayed_downloads)
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/martin/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
``

**Comment by LSB-dev** [comment]
I've just rechecked the code. It works on my side after changing the URL user agent. Please reopen the issue if it's still not working on your side.
